# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73ff9ea594fe628531b1d3e7e11a4f2933a0a0ed2a991a68a7f985ce812750147bd8dff3124fad864da8e7346df60fb8cc3133f509a256750d896e9cdf678e8c

test:
  secret_key_base: f078038745446aa516fc8cb52676dc8c9fcdc88a638fc95851bde4abc1e177c11ac500983927996198f1800ec4bcf181fbbdbcc864b2d778d232729beb201126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
