lines = {
  "1" => [
    {:name=>"Van Cortlandt Park - 242 St", :id=>"101"},
    {:name=>"238 St", :id=>"103"},
    {:name=>"231 St", :id=>"104"},
    {:name=>"Marble Hill - 225 St", :id=>"106"},
    {:name=>"215 St", :id=>"107"},
    {:name=>"207 St", :id=>"108"},
    {:name=>"Dyckman St", :id=>"109"},
    {:name=>"191 St", :id=>"110"},
    {:name=>"181 St", :id=>"111"},
    {:name=>"168 St - Washington Hts", :id=>"112"},
    {:name=>"157 St", :id=>"113"},
    {:name=>"145 St", :id=>"114"},
    {:name=>"137 St - City College", :id=>"115"},
    {:name=>"125 St", :id=>"116"},
    {:name=>"116 St - Columbia University", :id=>"117"},
    {:name=>"Cathedral Pkwy", :id=>"118"},
    {:name=>"103 St", :id=>"119"},
    {:name=>"96 St", :id=>"120"},
    {:name=>"86 St", :id=>"121"},
    {:name=>"79 St", :id=>"122"},
    {:name=>"72 St", :id=>"123"},
    {:name=>"66 St - Lincoln Center", :id=>"124"},
    {:name=>"59 St - Columbus Circle", :id=>"125"},
    {:name=>"50 St", :id=>"126"},
    {:name=>"Times Sq - 42 St", :id=>"127"},
    {:name=>"34 St - Penn Station", :id=>"128"},
    {:name=>"28 St", :id=>"129"},
    {:name=>"23 St", :id=>"130"},
    {:name=>"18 St", :id=>"131"},
    {:name=>"14 St", :id=>"132"},
    {:name=>"Christopher St - Sheridan Sq", :id=>"133"},
    {:name=>"Houston St", :id=>"134"},
    {:name=>"Canal St", :id=>"135"},
    {:name=>"Franklin St", :id=>"136"},
    {:name=>"Chambers St", :id=>"137"},
    {:name=>"Cortlandt St", :id=>"138"},
    {:name=>"Rector St", :id=>"139"},
    {:name=>"South Ferry Loop", :id=>"140"},
    {:name=>"South Ferry", :id=>"142"}],
  "2" => [ 
    {:name=>"Wakefield - 241 St", :id=>"201"},
    {:name=>"Nereid Av", :id=>"204"},
    {:name=>"233 St", :id=>"205"},
    {:name=>"225 St", :id=>"206"},
    {:name=>"219 St", :id=>"207"},
    {:name=>"Gun Hill Rd", :id=>"208"},
    {:name=>"Burke Av", :id=>"209"},
    {:name=>"Allerton Av", :id=>"210"},
    {:name=>"Pelham Pkwy", :id=>"211"},
    {:name=>"Bronx Park East", :id=>"212"},
    {:name=>"E 180 St", :id=>"213"},
    {:name=>"West Farms Sq - E Tremont Av", :id=>"214"},
    {:name=>"174 St", :id=>"215"},
    {:name=>"Freeman St", :id=>"216"},
    {:name=>"Simpson St", :id=>"217"},
    {:name=>"Intervale Av", :id=>"218"},
    {:name=>"Prospect Av", :id=>"219"},
    {:name=>"Jackson Av", :id=>"220"},
    {:name=>"3 Av - 149 St", :id=>"221"},
    {:name=>"149 St - Grand Concourse", :id=>"222"},
    {:name=>"135 St", :id=>"224"},
    {:name=>"125 St", :id=>"225"},
    {:name=>"116 St", :id=>"226"},
    {:name=>"Central Park North (110 St)", :id=>"227"},
    {:name=>"96 St", :id=>"120"},
    {:name=>"86 St", :id=>"121"},
    {:name=>"79 St", :id=>"122"},
    {:name=>"72 St", :id=>"123"},
    {:name=>"66 St - Lincoln Center", :id=>"124"},
    {:name=>"59 St - Columbus Circle", :id=>"125"},
    {:name=>"50 St", :id=>"126"},
    {:name=>"Times Sq - 42 St", :id=>"127"},
    {:name=>"34 St - Penn Station", :id=>"128"},
    {:name=>"28 St", :id=>"129"},
    {:name=>"23 St", :id=>"130"},
    {:name=>"18 St", :id=>"131"},
    {:name=>"14 St", :id=>"132"},
    {:name=>"Christopher St - Sheridan Sq", :id=>"133"},
    {:name=>"Houston St", :id=>"134"},
    {:name=>"Canal St", :id=>"135"},
    {:name=>"Franklin St", :id=>"136"},
    {:name=>"Chambers St", :id=>"137"},
    {:name=>"Park Pl", :id=>"228"},
    {:name=>"Fulton St", :id=>"229"},
    {:name=>"Wall St", :id=>"230"},
    {:name=>"Clark St", :id=>"231"},
    {:name=>"Borough Hall", :id=>"232"},
    {:name=>"Hoyt St", :id=>"233"},
    {:name=>"Nevins St", :id=>"234"},
    {:name=>"Atlantic Av", :id=>"235"},
    {:name=>"Bergen St", :id=>"236"},
    {:name=>"Grand Army Plaza", :id=>"237"},
    {:name=>"Eastern Pkwy - Brooklyn Museum", :id=>"238"},
    {:name=>"Franklin Av", :id=>"239"},
    {:name=>"President St", :id=>"241"},
    {:name=>"Sterling St", :id=>"242"},
    {:name=>"Winthrop St", :id=>"243"},
    {:name=>"Church Av", :id=>"244"},
    {:name=>"Beverly Rd", :id=>"245"},
    {:name=>"Newkirk Av", :id=>"246"},
    {:name=>"Flatbush Av - Brooklyn College", :id=>"247"}],
  "3" => [
    {:name=>"Harlem - 148 St", :id=>"301"},
    {:name=>"145 St", :id=>"302"},
    {:name=>"135 St", :id=>"224"},
    {:name=>"125 St", :id=>"225"},
    {:name=>"116 St", :id=>"226"},
    {:name=>"Central Park North (110 St)", :id=>"227"},
    {:name=>"96 St", :id=>"120"},
    {:name=>"72 St", :id=>"123"},
    {:name=>"Times Sq - 42 St", :id=>"127"},
    {:name=>"34 St - Penn Station", :id=>"128"},
    {:name=>"14 St", :id=>"132"},
    {:name=>"Chambers St", :id=>"137"},
    {:name=>"Park Pl", :id=>"228"},
    {:name=>"Fulton St", :id=>"229"},
    {:name=>"Wall St", :id=>"230"},
    {:name=>"Clark St", :id=>"231"},
    {:name=>"Borough Hall", :id=>"232"},
    {:name=>"Hoyt St", :id=>"233"},
    {:name=>"Nevins St", :id=>"234"},
    {:name=>"Atlantic Av", :id=>"235"},
    {:name=>"Bergen St", :id=>"236"},
    {:name=>"Grand Army Plaza", :id=>"237"},
    {:name=>"Eastern Pkwy - Brooklyn Museum", :id=>"238"},
    {:name=>"Franklin Av", :id=>"239"},
    {:name=>"Nostrand Av", :id=>"248"},
    {:name=>"Kingston Av", :id=>"249"},
    {:name=>"Crown Hts - Utica Av", :id=>"250"},
    {:name=>"Sutter Av - Rutland Rd", :id=>"251"},
    {:name=>"Saratoga Av", :id=>"252"},
    {:name=>"Rockaway Av", :id=>"253"},
    {:name=>"Junius St", :id=>"254"},
    {:name=>"Pennsylvania Av", :id=>"255"},
    {:name=>"Van Siclen Av", :id=>"256"},
    {:name=>"New Lots Av", :id=>"257"}],
  "4" => [
    {:name=>"Woodlawn", :id=>"401"},
    {:name=>"Mosholu Pkwy", :id=>"402"},
    {:name=>"Bedford Park Blvd - Lehman College", :id=>"405"},
    {:name=>"Kingsbridge Rd", :id=>"406"},
    {:name=>"Fordham Rd", :id=>"407"},
    {:name=>"183 St", :id=>"408"},
    {:name=>"Burnside Av", :id=>"409"},
    {:name=>"176 St", :id=>"410"},
    {:name=>"Mt Eden Av", :id=>"411"},
    {:name=>"170 St", :id=>"412"},
    {:name=>"167 St", :id=>"413"},
    {:name=>"161 St - Yankee Stadium", :id=>"414"},
    {:name=>"149 St - Grand Concourse", :id=>"415"},
    {:name=>"138 St - Grand Concourse", :id=>"416"},
    {:name=>"125 St", :id=>"621"},
    {:name=>"116 St", :id=>"622"},
    {:name=>"110 St", :id=>"623"},
    {:name=>"103 St", :id=>"624"},
    {:name=>"96 St", :id=>"625"},
    {:name=>"86 St", :id=>"626"},
    {:name=>"77 St", :id=>"627"},
    {:name=>"68 St - Hunter College", :id=>"628"},
    {:name=>"59 St", :id=>"629"},
    {:name=>"51 St", :id=>"630"},
    {:name=>"Grand Central - 42 St", :id=>"631"},
    {:name=>"33 St", :id=>"632"},
    {:name=>"28 St", :id=>"633"},
    {:name=>"23 St", :id=>"634"},
    {:name=>"14 St - Union Sq", :id=>"635"},
    {:name=>"Astor Pl", :id=>"636"},
    {:name=>"Bleecker St", :id=>"637"},
    {:name=>"Spring St", :id=>"638"},
    {:name=>"Canal St", :id=>"639"},
    {:name=>"Brooklyn Bridge - City Hall", :id=>"640"},
    {:name=>"Fulton St", :id=>"418"},
    {:name=>"Wall St", :id=>"419"},
    {:name=>"Bowling Green", :id=>"420"},
    {:name=>"Borough Hall", :id=>"423"},
    {:name=>"Nevins St", :id=>"234"},
    {:name=>"Atlantic Av", :id=>"235"},
    {:name=>"Bergen St", :id=>"236"},
    {:name=>"Grand Army Plaza", :id=>"237"},
    {:name=>"Eastern Pkwy - Brooklyn Museum", :id=>"238"},
    {:name=>"Franklin Av", :id=>"239"},
    {:name=>"Nostrand Av", :id=>"248"},
    {:name=>"Kingston Av", :id=>"249"},
    {:name=>"Crown Hts - Utica Av", :id=>"250"},
    {:name=>"Sutter Av - Rutland Rd", :id=>"251"},
    {:name=>"Saratoga Av", :id=>"252"},
    {:name=>"Rockaway Av", :id=>"253"},
    {:name=>"Junius St", :id=>"254"},
    {:name=>"Pennsylvania Av", :id=>"255"},
    {:name=>"Van Siclen Av", :id=>"256"},
    {:name=>"New Lots Av", :id=>"257"}],
  "5" => [
    {:name=>"Nereid Av", :id=>"204"},
    {:name=>"233 St", :id=>"205"},
    {:name=>"225 St", :id=>"206"},
    {:name=>"219 St", :id=>"207"},
    {:name=>"Gun Hill Rd", :id=>"208"},
    {:name=>"Burke Av", :id=>"209"},
    {:name=>"Allerton Av", :id=>"210"},
    {:name=>"Pelham Pkwy", :id=>"211"},
    {:name=>"Bronx Park East", :id=>"212"},
    {:name=>"E 180 St", :id=>"213"},
    {:name=>"West Farms Sq - E Tremont Av", :id=>"214"},
    {:name=>"174 St", :id=>"215"},
    {:name=>"Freeman St", :id=>"216"},
    {:name=>"Simpson St", :id=>"217"},
    {:name=>"Intervale Av", :id=>"218"},
    {:name=>"Prospect Av", :id=>"219"},
    {:name=>"Jackson Av", :id=>"220"},
    {:name=>"3 Av - 149 St", :id=>"221"},
    {:name=>"149 St - Grand Concourse", :id=>"222"},
    {:name=>"138 St - Grand Concourse", :id=>"416"},
    {:name=>"Eastchester - Dyre Av", :id=>"501"},
    {:name=>"Baychester Av", :id=>"502"},
    {:name=>"Gun Hill Rd", :id=>"503"},
    {:name=>"Pelham Pkwy", :id=>"504"},
    {:name=>"Morris Park", :id=>"505"},
    {:name=>"125 St", :id=>"621"},
    {:name=>"86 St", :id=>"626"},
    {:name=>"59 St", :id=>"629"},
    {:name=>"Grand Central - 42 St", :id=>"631"},
    {:name=>"14 St - Union Sq", :id=>"635"},
    {:name=>"Brooklyn Bridge - City Hall", :id=>"640"},
    {:name=>"Fulton St", :id=>"418"},
    {:name=>"Wall St", :id=>"419"},
    {:name=>"Bowling Green", :id=>"420"},
    {:name=>"Borough Hall", :id=>"423"},
    {:name=>"Nevins St", :id=>"234"},
    {:name=>"Atlantic Av", :id=>"235"},
    {:name=>"Franklin Av", :id=>"239"},
    {:name=>"President St", :id=>"241"},
    {:name=>"Sterling St", :id=>"242"},
    {:name=>"Winthrop St", :id=>"243"},
    {:name=>"Church Av", :id=>"244"},
    {:name=>"Beverly Rd", :id=>"245"},
    {:name=>"Newkirk Av", :id=>"246"},
    {:name=>"Flatbush Av - Brooklyn College", :id=>"247"}],
  "6" => [
    {:name=>"Pelham Bay Park", :id=>"601"},
    {:name=>"Buhre Av", :id=>"602"},
    {:name=>"Middletown Rd", :id=>"603"},
    {:name=>"Westchester Sq - E Tremont Av", :id=>"604"},
    {:name=>"Zerega Av", :id=>"606"},
    {:name=>"Castle Hill Av", :id=>"607"},
    {:name=>"Parkchester", :id=>"608"},
    {:name=>"St Lawrence Av", :id=>"609"},
    {:name=>"Morrison Av- Sound View", :id=>"610"},
    {:name=>"Elder Av", :id=>"611"},
    {:name=>"Whitlock Av", :id=>"612"},
    {:name=>"Hunts Point Av", :id=>"613"},
    {:name=>"Longwood Av", :id=>"614"},
    {:name=>"E 149 St", :id=>"615"},
    {:name=>"E 143 St - St Mary's St", :id=>"616"},
    {:name=>"Cypress Av", :id=>"617"},
    {:name=>"Brook Av", :id=>"618"},
    {:name=>"3 Av - 138 St", :id=>"619"},
    {:name=>"125 St", :id=>"621"},
    {:name=>"116 St", :id=>"622"},
    {:name=>"110 St", :id=>"623"},
    {:name=>"103 St", :id=>"624"},
    {:name=>"96 St", :id=>"625"},
    {:name=>"86 St", :id=>"626"},
    {:name=>"77 St", :id=>"627"},
    {:name=>"68 St - Hunter College", :id=>"628"},
    {:name=>"59 St", :id=>"629"},
    {:name=>"51 St", :id=>"630"},
    {:name=>"Grand Central - 42 St", :id=>"631"},
    {:name=>"33 St", :id=>"632"},
    {:name=>"28 St", :id=>"633"},
    {:name=>"23 St", :id=>"634"},
    {:name=>"14 St - Union Sq", :id=>"635"},
    {:name=>"Astor Pl", :id=>"636"},
    {:name=>"Bleecker St", :id=>"637"},
    {:name=>"Spring St", :id=>"638"},
    {:name=>"Canal St", :id=>"639"},
    {:name=>"Brooklyn Bridge - City Hall", :id=>"640"}],
  "S" => [
    {:name=>"Times Sq - 42 St", :id=>"902"},
    {:name=>"Grand Central - 42 St", :id=>"901"}]
}

lines.each do |train, stops|
  stops.each do |station|
    train = Train.find_or_create_by(name: train)
    station = Station.find_or_create_by(name: station[:name], station_id: station[:id])

    train.stations << station
  end
end